os: linux
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
sudo: required
env:
  - TARGET=
    CXX_FOR_TARGET=g++
  - TARGET=
    CXX_FOR_TARGET=clang++
  - TARGET=
    CXXFLAGS_FOR_TARGET="-O3 -fPIC -pie -Wall -static-libstdc++"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=clang++
    CXXFLAGS_FOR_TARGET="-m32 -march=i686 -O3 -Wall -static"
  - TARGET=i386-linux-gnu
    CXX_FOR_TARGET=clang++
    CXXFLAGS_FOR_TARGET="-m32 -march=i386 -O3 -Wall -static"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=clang++
    CXXFLAGS_FOR_TARGET="-m32 -march=i686 -O3 -fPIC -pie -Wall -static-libstdc++"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=g++-5
    CXXFLAGS_FOR_TARGET="-m32 -march=i686 -O3 -Wall -static"
  - TARGET=i386-linux-gnu
    CXX_FOR_TARGET=g++-5
    CXXFLAGS_FOR_TARGET="-m32 -march=i386 -O3 -Wall -static"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=g++-5
    CXXFLAGS_FOR_TARGET="-m32 -march=i686 -O3 -fPIC -pie -Wall -static-libstdc++"
  - TARGET=armv7-a-linux-gnueabi
  - TARGET=armv7-a-linux-gnueabi
    CXXFLAGS_FOR_TARGET="-O3 -fPIC -pie -Wall"
  - TARGET=armv6-linux-gnueabi
  - TARGET=armv4t-linux-gnueabi
  - TARGET=armv7-a-linux-gnueabihf
  - TARGET=armv7-a-linux-gnueabihf
    CXXFLAGS_FOR_TARGET="-O3 -fPIC -pie -Wall"
install: ./infra/travis-install-deps.sh
script: ./infra/travis-build-and-check.sh
