os: linux
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
sudo: required
env:
  - TARGET=
  - TARGET=
    CXX_FOR_TARGET=g++
    CXXFLAGS_FOR_TARGET="-static -O3 -fPIC -pie -Wall"
  - TARGET=
    CXX_FOR_TARGET=clang++
    CXXFLAGS_FOR_TARGET="-static -O3 -fPIC -pie -Wall"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=g++-5
    CXXFLAGS_FOR_TARGET="-m32 -static -O3 -fPIC -pie -Wall"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=clang++
    CXXFLAGS_FOR_TARGET="-m32 -static -O3 -fPIC -pie -Wall"
  - TARGET=i386-linux-gnu
    CXX_FOR_TARGET=g++-5
    CXXFLAGS_FOR_TARGET="-m32 -static -O3 -fPIC -pie -Wall"
  - TARGET=i386-linux-gnu
  - TARGET=armv7-a-linux-gnueabi
  - TARGET=armv6-linux-gnueabi
  - TARGET=armv4-linux-gnueabi
  - TARGET=armv4t-linux-gnueabi
install: ./infra/travis-install-deps.sh
script: ./infra/travis-build-and-check.sh
