os: linux
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
sudo: required
env:
  - TARGET=
    CXX_FOR_TARGET=g++
  - TARGET=
    CXX_FOR_TARGET=clang++
  - TARGET=
    CXXFLAGS_FOR_TARGET="-O3 -fPIC -pie -Wall -static-libstdc++"
  - TARGET=i686-linux-gnu
  - TARGET=i386-linux-gnu
  - TARGET=i686-linux-gnu
    CXXFLAGS_FOR_TARGET="-O3 -fPIC -pie -Wall -static-libstdc++"
  - TARGET=i686-linux-gnu
    CXX_FOR_TARGET=g++-5
  - TARGET=i386-linux-gnu
    CXX_FOR_TARGET=g++-5
  - TARGET=armv7-a-linux-gnueabi
  - TARGET=armv7-a-linux-gnueabi
    CXXFLAGS_FOR_TARGET="-O3 -fPIC -pie -Wall -static-libstdc++"
  - TARGET=armv6-linux-gnueabi
  - TARGET=armv4-linux-gnueabi
  - TARGET=armv4t-linux-gnueabi
install: ./infra/travis-install-deps.sh
script: ./infra/travis-build-and-check.sh
